services:
  devita-ai:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OLLAMA=http://ollama:11434
    container_name: devita-ai
    ports:
      - "8000:8000"
    depends_on:
      - ollama
      - vllm
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "8001:8001"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  vllm:
    image: vllm/vllm-openai
    container_name: vllm
    ports:
      - "8002:8002"